### ISSUE TITLE
Design main page

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/cosmos-telegram-signer#20]
- [x] login to the app with the pin or biometric
- [x] 4 times for pin enter, reset count after success, window with description what to do
- [x] network-based concept
- [x] valuation in usd/eth/btc
- [x] network chooser
- [x] currency chooser
- [x] qr-code for receive button to qr receive page
- [x] liquid balance in chosen currency
- [x] [staking window](#24) carousel
- [x] not claimed balance for staking
- [x] clickable address for copy
- [x] send button to [send page](#8)
- [x] receive button to [receive page](#6)
- [x] stake button to stake page
- [x] claim button to the [claim page](#10 )
- [x] search field to [search modal window](#22 )
- [x] clickable token fields with logo, denoms, amount and valuation, sort by valuation
- [x] title with number of available token denoms
